[package]
name = "jutils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poise = "0.6.1"
serenity = "0.12.1"
shuttle-secrets = "0.39.0"
tokio = { version = "1.36.0", features = ["full"] }
tracing = "0.1.40"
